### ISSUE TITLE
getBodyAsSource in java api doesn't work

### ISSUE THREAD

**Issue by huangd0ng** [playframework/play-ws#175]
### Play WS Version (2.5.x / etc)
2.6.1

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.12.5

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_121

### Library Dependencies
play-ws-standalone 1.0.1
(a play framework 2.6.1 project created with activator)

### Expected Behavior
getBodyAsSource returns  Source<ByteString, ?>

### Actual Behavior

Exception is thrown:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.ClassCastException: play.shaded.ahc.org.asynchttpclient.netty.NettyResponse cannot be cast to org.reactivestreams.Publisher]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:252)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
Caused by: java.util.concurrent.CompletionException: java.lang.ClassCastException: play.shaded.ahc.org.asynchttpclient.netty.NettyResponse cannot be cast to org.reactivestreams.Publisher
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Caused by: java.lang.ClassCastException: play.shaded.ahc.org.asynchttpclient.netty.NettyResponse cannot be cast to org.reactivestreams.Publisher
	at play.libs.ws.ahc.StandaloneAhcWSResponse.getBodyAsSource(StandaloneAhcWSResponse.java:125)
	at play.libs.ws.ahc.AhcWSResponse.getBodyAsSource(AhcWSResponse.java:87)
	at controllers.HomeController.lambda$index$0(HomeController.java:33)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

```

### Reproducible Test Case

```java
package controllers;

import com.google.inject.Inject;
import java.util.concurrent.CompletionStage;
import play.libs.ws.DefaultBodyReadables;
import play.libs.ws.WSClient;
import play.libs.ws.WSResponse;
import play.mvc.Controller;
import play.mvc.Result;

/**
 * This controller contains an action to handle HTTP requests
 * to the application's home page.
 */
public class HomeController extends Controller implements DefaultBodyReadables {

  private final WSClient wsClient;

  @Inject
  public HomeController(WSClient wsClient) {
    this.wsClient = wsClient;
  }

  /**
   * An action that renders an HTML page with a welcome message.
   * The configuration in the <code>routes</code> file means that
   * this method will be called when the application receives a
   * <code>GET</code> request with a path of <code>/</code>.
   */
  public CompletionStage<Result> index() {
    return wsClient.url("https://www.google.com")
        .get().thenApply(WSResponse::getBodyAsSource)
        .thenApply(body -> ok(views.html.index.render()));
  }
}
```

**Comment by huangd0ng** [comment]
I found it works in this way:
```java
wsClient.url("https://www.google.com")
        .stream().thenApply(WSResponse::getBodyAsSource)
```
I don't know if the exception is intentional

**Comment by marcospereira** [comment]
Hi @huangd0ng, it is not intentional. This should work just like the Scala version does.

Thanks for reporting this.

**Comment by marcospereira** [comment]
@huangd0ng see #180.

**Comment by marcospereira** [comment]
Hey @huangd0ng, could you please verify that version 1.0.4 solves this problem? You can add the following dependencies (temporarily) to test the new version:

```scala
libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play-ws-standalone" % "1.0.4",
  "com.typesafe.play" %% "play-ws-standalone-xml" % "1.0.4",
  "com.typesafe.play" %% "play-ws-standalone-json" % "1.0.4",
  "com.typesafe.play" %% "play-ahc-ws-standalone" % "1.0.4",
  "com.typesafe.play" % "shaded-asynchttpclient" % "1.0.4",
  "com.typesafe.play" % "shaded-oauth" % "1.0.4"
)
```

Thanks!

**Comment by huangd0ng** [comment]
@marcospereira it's working now. thanks
