### ISSUE TITLE
play2.7,HTTP header is larger than 8192 bytes

### ISSUE THREAD

**Issue by kingsant** [playframework/play-ws#333]
I update play 2.6 to 2.7. it happen to occure this exception。
play.server.akka.max-header-value-length = 32k can not solve this problem.
so how can i change the max value?

```
2019-04-22 16:13:51,131 [ERROR] [or.default-dispatcher-17]  [utils.ResponseUtil:30] msg: HTTP header is larger than 8192 bytes.. cause by: play.shaded.ahc.io.netty.handler.codec.TooLongFrameException: HTTP header is larger than 8192 bytes.
	at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.newException(HttpObjectDecoder.java:837)
	at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.process(HttpObjectDecoder.java:829)
	at play.shaded.ahc.io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1294)
	at play.shaded.ahc.io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1274)
	at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:801)
	at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder.readHeaders(HttpObjectDecoder.java:601)
	at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:227)
	at play.shaded.ahc.io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:202)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at play.shaded.ahc.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at play.shaded.ahc.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
	at play.shaded.ahc.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at play.shaded.ahc.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at play.shaded.ahc.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at play.shaded.ahc.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at play.shaded.ahc.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at play.shaded.ahc.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at play.shaded.ahc.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at play.shaded.ahc.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at play.shaded.ahc.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kingsant** [comment]
i resolve this problem now. add java option `-Dplay.shaded.ahc.org.asynchttpclient.httpClientCodecMaxHeaderSize=16000`

**Comment by ranjithv** [comment]
@kingsant: I'm having this issue in play 2.6.21 and adding java option is also not helping. Any other way to resolve this?

**Comment by llam15** [comment]
Is this the recommended solution for this issue? It seems unfortunate to have to manually set the shaded AHC property, when it worked in Play 2.6. Where is the regression happening?

**Comment by ranjithv** [comment]
For play prod mode, we have it like below in application.conf:
```
play.server {
  # The server provider class name
  provider = "play.core.server.AkkaHttpServerProvider"
  akka {
    max-uri-length = 16k
    max-header-value-length = 32k
  }
}
```
For dev mode, we have this in build.sbt. It seems to be running fine
```
PlayKeys.devSettings := Seq("play.server.provider" -> "play.core.server.AkkaHttpServerProvider",
  "play.server.akka.max-header-value-length" -> "32768",
  "akka.http.parsing.max-uri-length" -> "16k")
```

**Comment by mveroone** [comment]
> For play prod mode, we have it like below in application.conf:
> 
> ```
> play.server {
>   # The server provider class name
>   provider = "play.core.server.AkkaHttpServerProvider"
>   akka {
>     max-uri-length = 16k
>     max-header-value-length = 32k
>   }
> }
> ```
> 
> For dev mode, we have this in build.sbt. It seems to be running fine
> 
> ```
> PlayKeys.devSettings := Seq("play.server.provider" -> "play.core.server.AkkaHttpServerProvider",
>   "play.server.akka.max-header-value-length" -> "32768",
>   "akka.http.parsing.max-uri-length" -> "16k")
> ```
> 
> Our play is `2.6.23`

(I know we're 5 years later but for anyone looking at this)
This is the config for HTTP *requests*

> org.asynchttpclient.httpClientCodecMaxHeaderSize

is for HTTP responses.

You might need both but for different reasons. They're easy to confuse.
