### ISSUE TITLE
Can't use 2.1.4 with Java 8

### ISSUE THREAD

**Issue by maxcom** [playframework/play-ws#623]
Binaries was build on Java 11 and can't be used on Java 8:

```
2021-12-01T12:20:20+0300 ovm153 run[30329]: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.ahc.cache.CacheableResponse.getResponseBodyAsByteBuffer(CacheableResponse.scala:109)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.ahc.cache.CacheableResponse.getResponseBodyAsBytes(CacheableResponse.scala:100)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.ahc.cache.CacheableResponse.getResponseBody(CacheableResponse.scala:132)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.ahc.AhcWSUtils$.getResponseBody(AhcWSUtils.scala:17)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.ahc.StandaloneAhcWSResponse.body$lzycompute(StandaloneAhcWSResponse.scala:39)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.ahc.StandaloneAhcWSResponse.body(StandaloneAhcWSResponse.scala:38)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.JsonBodyReadables.$anonfun$readableAsJson$1(JsonBodyReadables.scala:27)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.StandaloneWSResponse.body(StandaloneWSResponse.scala:112)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.StandaloneWSResponse.body$(StandaloneWSResponse.scala:110)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.ahc.StandaloneAhcWSResponse.body(StandaloneAhcWSResponse.scala:17)
2021-12-01T12:20:20+0300 ovm153 run[30329]:         at play.api.libs.ws.ahc.AhcWSResponse.json(AhcWSResponse.scala:93)
```

This is well know problem (see https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/ for explanaition). Please rebuild them under Java 8 so they will be compatible with 8 and any modern version of JDK.

**Comment by octonato** [comment]
@maxcom, thanks for reporting this. 

I just published version 2.1.6 build with JDK8. Could you test it out?

**Comment by maxcom** [comment]
Thank you for fast fix. Our application start fine with 2.1.6 (it crashed on start before this fix). 

CI and other tests will run at night. I will let you know if a similar problem occurs.

**Comment by octonato** [comment]
Great to hear it. 

I'm closing this issue for know. Please, don't hesitate to re-open it if needed.

**Comment by maxcom** [comment]
Found similar issue in play core: https://github.com/playframework/playframework/issues/11033
